sudo: required

language: java

services:
  - docker

before_install:
  - docker build -t green .
  - docker ps -a
  - docker run green /bin/sh -c "cd /root/green; ant; ant test"

script:
  - docker run green /bin/sh -c "ant; ant test;"
  - ant; ant test;

#Please note, then second "ant; ant test" was used to show failures for JUnit tests.